UPDATE sys_menu SET name = '项目管理' WHERE code = 'project';
UPDATE sys_menu SET name = '任务管理' WHERE code = 'task';
UPDATE sys_menu SET name = '需求管理' WHERE code = 'requirement';
UPDATE sys_menu SET name = 'Bug 管理' WHERE code = 'bug';
UPDATE sys_menu SET name = '查看操作日志' WHERE code = 'system:log:view';
UPDATE sys_menu SET name = '查看用户' WHERE code = 'system:user:view';
UPDATE sys_menu SET name = '创建用户' WHERE code = 'system:user:create';
UPDATE sys_menu SET name = '更新用户' WHERE code = 'system:user:update';
UPDATE sys_menu SET name = '查看部门' WHERE code = 'system:department:view';
UPDATE sys_menu SET name = '创建部门' WHERE code = 'system:department:create';
UPDATE sys_menu SET name = '更新部门' WHERE code = 'system:department:update';
UPDATE sys_menu SET name = '查看角色' WHERE code = 'system:role:view';
UPDATE sys_menu SET name = '创建角色' WHERE code = 'system:role:create';
UPDATE sys_menu SET name = '更新角色' WHERE code = 'system:role:update';
UPDATE sys_menu SET name = '分配角色菜单' WHERE code = 'system:role:assign-menu';
UPDATE sys_menu SET name = '查看菜单' WHERE code = 'system:menu:view';
UPDATE sys_menu SET name = '创建菜单' WHERE code = 'system:menu:create';
UPDATE sys_menu SET name = '更新菜单' WHERE code = 'system:menu:update';
UPDATE sys_menu SET name = '创建项目' WHERE code = 'project:create';
UPDATE sys_menu SET name = '更新项目' WHERE code = 'project:update';
UPDATE sys_menu SET name = '创建任务' WHERE code = 'task:create';
UPDATE sys_menu SET name = '更新任务' WHERE code = 'task:update';
UPDATE sys_menu SET name = '创建需求' WHERE code = 'requirement:create';
UPDATE sys_menu SET name = '更新需求' WHERE code = 'requirement:update';
UPDATE sys_menu SET name = '创建 Bug' WHERE code = 'bug:create';
UPDATE sys_menu SET name = '更新 Bug' WHERE code = 'bug:update';
UPDATE sys_menu SET name = '文件管理' WHERE code = 'file';
UPDATE sys_menu SET name = '上传文件' WHERE code = 'file:upload';
UPDATE sys_menu SET name = '删除文件' WHERE code = 'file:delete';
UPDATE sys_menu SET name = '日报管理' WHERE code = 'daily-report';
UPDATE sys_menu SET name = '创建日报' WHERE code = 'daily-report:create';
UPDATE sys_menu SET name = '更新日报' WHERE code = 'daily-report:update';
UPDATE sys_menu SET name = '项目汇报管理' WHERE code = 'project-report';
UPDATE sys_menu SET name = '创建项目汇报' WHERE code = 'project-report:create';
UPDATE sys_menu SET name = '更新项目汇报' WHERE code = 'project-report:update';